[package]
name = "nightcycle/polytope"
description = "A helper library for easier handling of the hierarchy of dimensional constructs often utilized in procedural generation and dynamic placement of 3D objects."
version = "0.1.0"
license = "Apache"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = ["src", "default.project.json", "LICENSE"]

[dependencies]
Draw = "nightcycle/draw@1.0.6"
TableUtil = "nightcycle/table-util@3.1.0"

[dev-dependencies]
UILabs = "pepeeltoro41/ui-labs@2.4.2"
Osiris = "nightcycle/osiris@0.1.3"